### PR TITLE
[Woo] Allow signing in to WPCom black-flagged websites using site credentials

### LINKED ISSUE #12779: Direct black-flagged websites to use site credentials instead of failing.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: https://github.com/woocommerce/woocommerce-android/issues/12779

Depends on https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3107

This PR updates the login flow for Woo to allow signing in to WordPress.com black-flagged websites, those websites will be treated as not having Jetpack, and will then be directed to the site credentials login flow.

### Testing
For testing, please check https://github.com/woocommerce/woocommerce-android/pull/12780

### CODE REVIEW

File: WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginListener.java [hunk 1]
```diff
@@ -61,7 +61,11 @@ void needs2faSocial(String email, String userId, String nonceAuthenticator, Stri
     // Login Site Address input callbacks
     void alreadyLoggedInWpcom(ArrayList<Integer> oldSitesIds);
     void gotWpcomSiteInfo(String siteAddress);
-    void gotConnectedSiteInfo(@NonNull String siteAddress, @Nullable String redirectUrl, boolean hasJetpack);
+    default void gotConnectSiteInfo(@NonNull ConnectSiteInfoResult result) {
+        gotConnectedSiteInfo(result.getUrl(), result.getUrlAfterRedirects(), result.getHasJetpack());
+    }
+
```
Comment (hichamboushaba) [inline WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginListener.java:67]: With these default implementations, we can avoid making this a breaking change for the client apps, for now, the apps will keep overriding the old version `gotConnectedSiteInfo`, while for WCAndroid, we will soon migrate to the new one `gotConnectSiteInfo` that passes the new model `ConnectSiteInfoResult` which would allow us to know if the site is suspended.

File: WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java [hunk 2]
```diff
@@ -339,15 +340,7 @@ public void handleDiscoverySuccess(@NonNull String endpointAddress) {
...
         endProgress();
-        if (mLoginListener.getLoginMode() == LoginMode.WOO_LOGIN_MODE) {
-            mLoginListener.gotConnectedSiteInfo(
-                    mConnectSiteInfoUrl,
-                    mConnectSiteInfoUrlRedirect,
-                    mConnectSiteInfoCalculatedHasJetpack
-                                               );
-        } else {
-            mLoginListener.gotXmlRpcEndpoint(inputSiteAddress, endpointAddress);
-        }
```
Comment (JorgeMucientes) [inline WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java:350]: Hmm, I'm missing context here on why this check is not needed anymore and we can always default to `mLoginListener.gotXmlRpcEndpoint`. Could please share some? 🙏🏼

**Review by JorgeMucientes — APPROVED** [review]

File: WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java (hunk 2 above)
Comment (hichamboushaba) [reply WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java:350]: Sorry for not sharing context regarding this change 🙏 

This logic (`handleDiscoverySuccess`) is called only when we use the XMLRPC discovery, and we don't use it anymore for Woo (https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/pull/109)

Comment (JorgeMucientes) [reply WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java:350]: Thanks for clarifying!
